---
name: Neovim
on:
  pull_request:
  push:
    paths-ignore:
      - "*.md"
    branches:
      - main

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Neovim
        uses: MunifTanjim/setup-neovim-action@v1
        with:
          tag: nightly
      - name: Run neovim
        run: |
          nvim --version
          nvim --headless -u tests/init.lua +q
